import pandas as pd
import numpy as np
from .base import BaseStrategy


# Configuraciones optimas por activo (de ma_optima.pine / ma_optimizer.py v2)
MA_OPTIMA_CONFIGS = {
    "MSFT":  ("EMA", 50, 130),
    "GOOGL": ("EMA", 45, 65),
    "NVDA":  ("EMA", 50, 55),
    "META":  ("EMA", 35, 60),
    "AMZN":  ("SMA", 15, 195),
    "MELI":  ("SMA", 50, 200),
    "MSTR":  ("SMA", 15, 195),
    "GGAL":  ("WMA", 15, 35),
    "BMA":   ("WMA", 15, 40),
    "AVGO":  ("SMA", 10, 140),
}


def _calc_wma(series: pd.Series, period: int) -> pd.Series:
    weights = np.arange(1, period + 1, dtype=float)
    return series.rolling(period).apply(
        lambda x: np.dot(x, weights) / weights.sum(), raw=True
    )


def _calc_ma(series: pd.Series, ma_type: str, period: int) -> pd.Series:
    if ma_type == "EMA":
        return series.ewm(span=period, adjust=False).mean()
    elif ma_type == "WMA":
        return _calc_wma(series, period)
    else:  # SMA
        return series.rolling(period).mean()


class MAOptima(BaseStrategy):
    """
    Crossover strategy using per-symbol optimized MA type and periods.
    Ported from ma_optima.pine (generated by ma_optimizer.py v2).

    Long when fast MA > slow MA, flat otherwise.
    """

    def __init__(self, ma_type: str = "SMA", fast: int = 50, slow: int = 200,
                 symbol: str = ""):
        self.ma_type = ma_type.upper()
        self.fast = fast
        self.slow = slow
        self.symbol = symbol

    @property
    def name(self) -> str:
        label = f"MAOpt-{self.ma_type}({self.fast},{self.slow})"
        return label

    def generate_signals(self, prices: pd.Series) -> pd.Series:
        ma_fast = _calc_ma(prices, self.ma_type, self.fast)
        ma_slow = _calc_ma(prices, self.ma_type, self.slow)
        signal = (ma_fast > ma_slow).astype(int)
        return signal.fillna(0)
